import Head from "next/head";
import Image from "next/image";
import DashboardLayout from "../layouts/dashboard";
import {
  Box,
  Container,
  Flex,
  Heading,
  Text,
  Divider,
  Span,
  Link as ChakraLink,
  useColorMode,
} from "@chakra-ui/react";
import AuthLogin from "../components/Auth/AuthLogin";
import Link from "next/link";
import { useEffect, useContext, useState } from "react";
import { TempContext } from "../context/TempContext";
import instance from "../axios.default";
import { ProtectedRoute } from "../HOC/withAuth";

function Home() {
  const [settings, setSettings] = useContext(TempContext);

  const fetchUserLogin = async () => {
    try {
      const result = await instance.get("/SuperAdmin/profile");
      setSettings({ ...settings, userLogin: result.data.data });
    } catch (error) {
      alert(error);
    }
  };

  useEffect(() => {
    fetchUserLogin();
  }, []);

  return (
    <div>
      <Head>
        <title>E-ROR | Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>Test</DashboardLayout>
    </div>
  );
}

export default ProtectedRoute(Home);
